# Generated by Django 6.0 on 2025-12-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('targeted_stat', models.JSONField()),
                ('description', models.TextField()),
                ('difficulty', models.CharField(max_length=6)),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.PositiveIntegerField()),
                ('stats', models.JSONField()),
                ('progress', models.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.PositiveIntegerField(),
        ),
    ]
