# Generated by Django 6.0 on 2025-12-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_badge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badge',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='badge',
            old_name='Title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='level',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
