
POST http://127.0.0.1:8000/login
Content-Type: application/json

{"email" : "Loubna@gmail.com" , "password" : "Password123!"}


###

POST http://127.0.0.1:8000/signup
Content-Type: application/json

{"username" : "Fayza" , "password" : "Password123!" , "email" : "Fayza@gmail.com" , "age" : 11}

###

GET http://127.0.0.1:8000/test_token
Content-Type: application/json
Authorization: Token 


{}
###
GET http://127.0.0.1:8000/Users
Content-Type: application/json
Authorization: Token 00d6ac79bcd4ce5c623a1246b1e95145529c8e52

{}
###
GET http://127.0.0.1:8000/friend_requests/
Content-Type: application/json
Authorization: Token 0473763117c883e8f3265d065c6201ad0fb8e580

{}
###
POST http://127.0.0.1:8000/send_friend_request/10/
Content-Type: application/json
Authorization: Token c59d51645d97a29bc4a3b1b733113f11bf6fb946


{}
###
GET http://127.0.0.1:8000/my_friends/
Content-Type: application/json
Authorization: Token c59d51645d97a29bc4a3b1b733113f11bf6fb946


{}
###
PATCH http://127.0.0.1:8000/accept_friend_request/4/
Content-Type: application/json
Authorization: Token 00d6ac79bcd4ce5c623a1246b1e95145529c8e52

{}
###
DELETE http://127.0.0.1:8000/decline_friend_request/8/
Content-Type: application/json
Authorization: Token 0473763117c883e8f3265d065c6201ad0fb8e580

{}
###

GET http://127.0.0.1:8000/Badge/11/
Content-Type: aaplication/json 

{}