
POST http://127.0.0.1:8000/login
Content-Type: application/json

{"username" : "admin" , "password" : "Password123!"}


###

POST http://127.0.0.1:8000/signup
Content-Type: application/json

{"username" : "DUDE" , "password" : "Password123!" , "email" : "Dude@gmail.com" , "age" : 18}

###

GET http://127.0.0.1:8000/test_token
Content-Type: application/json
Authorization: Token 0473763117c883e8f3265d065c6201ad0fb8e580

{}
###
GET http://127.0.0.1:8000/get_stats
Content-Type: application/json
Authorization: Token 0473763117c883e8f3265d065c6201ad0fb8e580

{}
###
GET http://127.0.0.1:8000/friend_requests/
Content-Type: application/json
Authorization: Token 0473763117c883e8f3265d065c6201ad0fb8e580

{}
###
POST http://127.0.0.1:8000/send_friend_request/5/
Content-Type: application/json
Authorization: Token 0473763117c883e8f3265d065c6201ad0fb8e580


{}
###
GET http://127.0.0.1:8000/my_friends/
Content-Type: application/json
Authorization: Token 0473763117c883e8f3265d065c6201ad0fb8e580


{}
###
PATCH http://127.0.0.1:8000/accept_friend_request/2/
Content-Type: application/json
Authorization: Token 0473763117c883e8f3265d065c6201ad0fb8e580

{}
###
DELETE http://127.0.0.1:8000/decline_friend_request/8/
Content-Type: application/json
Authorization: Token 0473763117c883e8f3265d065c6201ad0fb8e580

{}
###